project:
  type: website
  output-dir: docs

website:
  title: "Jaeho-Jung's blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Jaeho-Jung
      # - icon: twitter
      #   href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css



